version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    environment:
      - POSTGRES_PASSWORD=12345
    env_file:
      - .env.development
    volumes:
      - postgres:/var/lib/postgresql/data
    
  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env.development
volumes:
  postgres: